### ISSUE TITLE
0.8.2 cannot find conf/server-cert.pem

### ISSUE THREAD

**Issue by sjcorbett** [brooklyncentral/clocker#122]
Downloaded v0.8.2 from clocker.io and ran `./bin/clocker.sh jclouds:softlayer:ams01`. The installation of the DockerHosts failed with this exception:

```
2015-06-23 18:41:26,707 WARN  b.e.b.AbstractSoftwareProcessDriver [brooklyn-execmanager-uSWx77bc-85]: Error copying runtime resources
java.lang.RuntimeException: Error getting resource 'conf/server-cert.pem' for DockerHostImpl{id=AxGXNjjR}: java.io.IOException: 'conf/server-cert.pem' not found on classpath or filesystem
	at brooklyn.util.ResourceUtils.getResourceFromUrl(ResourceUtils.java:290) ~[brooklyn-core-0.7.0-20150603.164010-253.jar:0.7.0-SNAPSHOT]
	at brooklyn.location.basic.SshMachineLocation.installTo(SshMachineLocation.java:809) ~[brooklyn-core-0.7.0-20150603.164010-253.jar:0.7.0-SNAPSHOT]
	at brooklyn.entity.basic.AbstractSoftwareProcessSshDriver.copyResource(AbstractSoftwareProcessSshDriver.java:368) ~[brooklyn-software-base-0.7.0-20150603.164055-252.jar:0.7.0-SNAPSHOT]
	at brooklyn.entity.basic.AbstractSoftwareProcessDriver.copyResource(AbstractSoftwareProcessDriver.java:417) ~[brooklyn-software-base-0.7.0-20150603.164055-252.jar:0.7.0-SNAPSHOT]
	at brooklyn.entity.basic.AbstractSoftwareProcessDriver.copyRuntimeResources(AbstractSoftwareProcessDriver.java:346) ~[brooklyn-software-base-0.7.0-20150603.164055-252.jar:0.7.0-SNAPSHOT]
	at brooklyn.entity.basic.AbstractSoftwareProcessDriver$9.run(AbstractSoftwareProcessDriver.java:155) [brooklyn-software-base-0.7.0-20150603.164055-252.jar:0.7.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_51]
	at brooklyn.util.task.DynamicSequentialTask$DstJob.call(DynamicSequentialTask.java:337) [brooklyn-core-0.7.0-20150603.164010-253.jar:0.7.0-SNAPSHOT]
	at brooklyn.util.task.BasicExecutionManager$SubmissionCallable.call(BasicExecutionManager.java:469) [brooklyn-core-0.7.0-20150603.164010-253.jar:0.7.0-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_51]
	at java.lang.Thread.run(Thread.java:744) [na:1.7.0_51]
Caused by: java.io.IOException: 'conf/server-cert.pem' not found on classpath or filesystem
	at brooklyn.util.ResourceUtils.getResourceFromUrl(ResourceUtils.java:287) ~[brooklyn-core-0.7.0-20150603.164010-253.jar:0.7.0-SNAPSHOT]
	... 12 common frames omitted
```

**Comment by sjcorbett** [comment]
The missing file definitely exists on disk, by the way.

**Comment by sjcorbett** [comment]
... and I have the same problem with a build of `master/HEAD`.

**Comment by sjcorbett** [comment]
`conf/server-cert.pem` should be replaced with `server-cert.pem`.

**Comment by sjcorbett** [comment]
After investigation with @csabapalfi we realise that Clocker MUST be run from the root of the distribution directory. Running from any other directory causes failure. Certain parts of Clocker expect `conf/server-cert.pem` to be on the classpath so #123 as it is is insufficient.

**Comment by csabapalfi** [comment]
The reason why it only works from a specific directory:
* the directory where clocker.sh is ran from ends up on the classpath
* when clocker.sh is ran from the distribution directory /conf is on the classpath
* therefore `conf/server-cert.pem` is available on the classpath

**Comment by grkvlt** [comment]
@csabapalfi can you look at fixing `clocker.sh` to handle running from arbitrary directories, so set the path based on `$0` and the assumption that relative to the script libraries are in `../library/*` and so on.

**Comment by csabapalfi** [comment]
clocker.sh resolves all the directories correctly but clocker assumes that the distribution directory (BROOKLYN_HOME) is on the classpath. See https://github.com/brooklyncentral/clocker/pull/127 with a fix so that we can run clocker.sh from anywhere.

**Comment by grkvlt** [comment]
@sjcorbett closing as fixed with latest code
