### ISSUE TITLE
Exception parsing JSON when provisioning container

### ISSUE THREAD

**Issue by sjcorbett** [brooklyncentral/clocker#126]
Approximately 10% of containers I attempt to provision fail immediately with this exception:

```
2015-06-24 10:06:19,793 ERROR o.j.http.functions.ParseJson [brooklyn-execmanager-H8ch5nak-298]: Error parsing input: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 958 path $.HostConfig.Dns
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 958 path $.HostConfig.Dns
	at org.jclouds.json.internal.DeserializationConstructorAndReflectiveTypeAdapterFactory$DeserializeIntoParameterizedConstructor.read(DeserializationConstructorAndReflectiveTypeAdapterFactory.java:190) ~[jclouds-core-1.9.0.jar:1.9.0]
	at org.jclouds.json.internal.DeserializationConstructorAndReflectiveTypeAdapterFactory$ParameterReader.read(DeserializationConstructorAndReflectiveTypeAdapterFactory.java:272) ~[jclouds-core-1.9.0.jar:1.9.0]
	at org.jclouds.json.internal.DeserializationConstructorAndReflectiveTypeAdapterFactory$DeserializeIntoParameterizedConstructor.read(DeserializationConstructorAndReflectiveTypeAdapterFactory.java:184) ~[jclouds-core-1.9.0.jar:1.9.0]
	at com.google.gson.Gson.fromJson(Gson.java:805) ~[gson-2.3.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:770) ~[gson-2.3.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:719) ~[gson-2.3.jar:na]
	at org.jclouds.json.internal.GsonWrapper.fromJson(GsonWrapper.java:42) ~[jclouds-core-1.9.0.jar:1.9.0]
	at org.jclouds.http.functions.ParseJson.apply(ParseJson.java:83) [jclouds-core-1.9.0.jar:1.9.0]
	at org.jclouds.http.functions.ParseJson.apply(ParseJson.java:77) [jclouds-core-1.9.0.jar:1.9.0]
	at org.jclouds.http.functions.ParseJson.apply(ParseJson.java:62) [jclouds-core-1.9.0.jar:1.9.0]
	at org.jclouds.http.functions.ParseJson.apply(ParseJson.java:42) [jclouds-core-1.9.0.jar:1.9.0]
	at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:90) [jclouds-core-1.9.0.jar:1.9.0]
	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:73) [jclouds-core-1.9.0.jar:1.9.0]
	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:44) [jclouds-core-1.9.0.jar:1.9.0]
	at org.jclouds.reflect.FunctionalReflection$FunctionalInvocationHandler.handleInvocation(FunctionalReflection.java:117) [jclouds-core-1.9.0.jar:1.9.0]
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87) [guava-17.0.jar:na]
	at com.sun.proxy.$Proxy172.inspectContainer(Unknown Source) [na:na]
	at org.jclouds.docker.compute.strategy.DockerComputeServiceAdapter.listNodes(DockerComputeServiceAdapter.java:212) [brooklyn-clocker-docker-0.9.0-SNAPSHOT.jar:na]
	at org.jclouds.compute.strategy.impl.AdaptingComputeServiceStrategies.listDetailsOnNodesMatching(AdaptingComputeServiceStrategies.java:122) [jclouds-compute-1.9.0.jar:1.9.0]
	at org.jclouds.compute.strategy.impl.AdaptingComputeServiceStrategies.listNodes(AdaptingComputeServiceStrategies.java:112) [jclouds-compute-1.9.0.jar:1.9.0]
	at org.jclouds.compute.strategy.impl.CreateNodesWithGroupEncodedIntoNameThenAddToSet.getNextNames(CreateNodesWithGroupEncodedIntoNameThenAddToSet.java:192) [jclouds-compute-1.9.0.jar:1.9.0]
	at org.jclouds.compute.strategy.impl.CreateNodesWithGroupEncodedIntoNameThenAddToSet.execute(CreateNodesWithGroupEncodedIntoNameThenAddToSet.java:121) [jclouds-compute-1.9.0.jar:1.9.0]
	at org.jclouds.compute.internal.BaseComputeService.createNodesInGroup(BaseComputeService.java:210) [jclouds-compute-1.9.0.jar:1.9.0]
	at brooklyn.location.jclouds.JcloudsLocation.obtainOnce(JcloudsLocation.java:686) [brooklyn-locations-jclouds-0.7.0-20150615.084013-254.jar:0.7.0-SNAPSHOT]
	at brooklyn.location.jclouds.JcloudsLocation.obtain(JcloudsLocation.java:581) [brooklyn-locations-jclouds-0.7.0-20150615.084013-254.jar:0.7.0-SNAPSHOT]
	at brooklyn.entity.container.docker.DockerContainerImpl.createLocation(DockerContainerImpl.java:453) [brooklyn-clocker-docker-0.9.0-SNAPSHOT.jar:na]
	at brooklyn.entity.container.docker.DockerContainerImpl.start(DockerContainerImpl.java:570) [brooklyn-clocker-docker-0.9.0-SNAPSHOT.jar:na]
	at sun.reflect.GeneratedMethodAccessor66.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_51]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_51]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90) [groovy-all-2.3.4.jar:2.3.4]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233) [groovy-all-2.3.4.jar:2.3.4]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1085) [groovy-all-2.3.4.jar:2.3.4]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909) [groovy-all-2.3.4.jar:2.3.4]
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:149) [groovy-all-2.3.4.jar:2.3.4]
	at groovy.lang.MetaObjectProtocol$invokeMethod.call(Unknown Source) [groovy-all-2.3.4.jar:2.3.4]
	at brooklyn.util.GroovyJavaMethods.invokeMethodOnMetaClass(GroovyJavaMethods.groovy:144) [brooklyn-utils-groovy-0.7.0-20150615.084055-253.jar:0.7.0-SNAPSHOT]
	at brooklyn.management.internal.AbstractManagementContext.invokeEffectorMethodLocal(AbstractManagementContext.java:286) [brooklyn-core-0.7.0-20150615.083911-254.jar:0.7.0-SNAPSHOT]
	at brooklyn.management.internal.AbstractManagementContext.invokeEffectorMethodSync(AbstractManagementContext.java:310) [brooklyn-core-0.7.0-20150615.083911-254.jar:0.7.0-SNAPSHOT]
	at brooklyn.management.internal.EffectorUtils.invokeMethodEffector(EffectorUtils.java:250) [brooklyn-core-0.7.0-20150615.083911-254.jar:0.7.0-SNAPSHOT]
	at brooklyn.entity.basic.MethodEffector.call(MethodEffector.java:149) [brooklyn-core-0.7.0-20150615.083911-254.jar:0.7.0-SNAPSHOT]
	at brooklyn.entity.trait.Startable$StartEffectorBody.call(Startable.java:57) [brooklyn-core-0.7.0-20150615.083911-254.jar:0.7.0-SNAPSHOT]
	at brooklyn.entity.trait.Startable$StartEffectorBody.call(Startable.java:51) [brooklyn-core-0.7.0-20150615.083911-254.jar:0.7.0-SNAPSHOT]
	at brooklyn.entity.effector.EffectorTasks$EffectorBodyTaskFactory$1.call(EffectorTasks.java:83) [brooklyn-core-0.7.0-20150615.083911-254.jar:0.7.0-SNAPSHOT]
	at brooklyn.util.task.DynamicSequentialTask$DstJob.call(DynamicSequentialTask.java:337) [brooklyn-core-0.7.0-20150615.083911-254.jar:0.7.0-SNAPSHOT]
	at brooklyn.util.task.BasicExecutionManager$SubmissionCallable.call(BasicExecutionManager.java:469) [brooklyn-core-0.7.0-20150615.083911-254.jar:0.7.0-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_51]
	at java.lang.Thread.run(Thread.java:744) [na:1.7.0_51]
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 958 path $.HostConfig.Dns
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:836) ~[gson-2.3.jar:na]
	at com.google.gson.internal.bind.TypeAdapters$13.read(TypeAdapters.java:358) ~[gson-2.3.jar:na]
	at com.google.gson.internal.bind.TypeAdapters$13.read(TypeAdapters.java:346) ~[gson-2.3.jar:na]
	at org.jclouds.json.internal.DeserializationConstructorAndReflectiveTypeAdapterFactory$ParameterReader.read(DeserializationConstructorAndReflectiveTypeAdapterFactory.java:272) ~[jclouds-core-1.9.0.jar:1.9.0]
	at org.jclouds.json.internal.DeserializationConstructorAndReflectiveTypeAdapterFactory$DeserializeIntoParameterizedConstructor.read(DeserializationConstructorAndReflectiveTypeAdapterFactory.java:184) ~[jclouds-core-1.9.0.jar:1.9.0]
	... 49 common frames omitted
```

The following is the line of the jclouds log immediately before the exception above was thrown:
```
2015-06-24 10:06:19,790 DEBUG jclouds.wire [brooklyn-execmanager-H8ch5nak-298]: << "{"AppArmorProfile":"","Args":["-D"],"Config":{"AttachStderr":false,"AttachStdin":false,"AttachStdout":false,"Cmd":["/usr/sbin/sshd","-D"],"CpuShares":0,"Cpuset":"","Domainname":"","Entrypoint":[],"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"ExposedPorts":{"22/tcp":{},"4369/tcp":{},"6000/tcp":{},"7999/tcp":{},"8087/tcp":{},"8093/tcp":{},"8098/tcp":{},"8099/tcp":{},"8985/tcp":{}},"Hostname":"acb3b897cc81","Image":"eeb870a58a73279a845f97b4d351c7fdcea9e9f268dc39b04861f526328e9f95","Labels":{},"MacAddress":"","Memory":0,"MemorySwap":0,"NetworkDisabled":false,"OnBuild":null,"OpenStdin":false,"PortSpecs":null,"StdinOnce":false,"Tty":false,"User":"","Volumes":null,"WorkingDir":""},"Created":"2015-06-24T09:06:19.59166437Z","Driver":"overlay","ExecDriver":"native-0.2","ExecIDs":null,"HostConfig":{"Binds":[],"CapAdd":[],"CapDrop":[],"CgroupParent":"","ContainerIDFile":"","CpuShares":0,"CpusetCpus":"","Devices":null,"Dns":[],"DnsSearch":null,"ExtraHosts":null,"IpcMode":"","Links":null,"LogConfig":{"Config":null,"Type":"json-file"},"LxcConf":[],"Memory":0,"MemorySwap":0,"NetworkMode":"","PidMode":"","PortBindings":{},"Privileged":false,"PublishAllPorts":false,"ReadonlyRootfs":false,"RestartPolicy":{"MaximumRetryCount":0,"Name":""},"SecurityOpt":null,"Ulimits":null,"VolumesFrom":null},"HostnamePath":"","HostsPath":"","Id":"acb3b897cc814fbe38b819a85edfbda14c4aab8e7df25200a4d85db79fc2fef7","Image":"eeb870a58a73279a845f97b4d351c7fdcea9e9f268dc39b04861f526328e9f95","LogPath":"","MountLabel":"","Name":"/brooklyn-pshh-sam-8ac","NetworkSettings":{"Bridge":"","Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","LinkLocalIPv6Address":"","LinkLocalIPv6PrefixLen":0,"MacAddress":"","PortMapping":null,"Ports":null},"Path":"/usr/sbin/sshd","ProcessLabel":"","ResolvConfPath":"","RestartCount":0,"State":{"Dead":false,"Error":"","ExitCode":0,"FinishedAt":"0001-01-01T00:00:00Z","OOMKilled":false,"Paused":false,"Pid":0,"Restarting":false,"Running":false,"StartedAt":"0001-01-01T00:00:00Z"},"Volumes":{},"VolumesRW":{}}[\n]"
```

**Comment by grkvlt** [comment]
Fixed by https://github.com/jclouds/jclouds-labs/pull/178 now, but need to update the patch before it can be merged, will check with @andreaturli about backporting to 1.9.x stream

**Comment by grkvlt** [comment]
Fixed in current version of jclouds Docker provider as used by Clocker, so closing.
