### ISSUE TITLE
Error bringing up 2 node docker cluster on EC2, calico node error

### ISSUE THREAD

**Issue by bitsofinfo** [brooklyncentral/clocker#149]
Hi 
Been getting this error when trying to spin up a cluster in ec2, I've gotten a similar error when I select Weave. I've been using the latest distro available under releases

```
2015-08-25 08:41:52,263 INFO  Adding first node EtcdClusterImpl{id=Fsa4HRJC}: EtcdNodeImpl{id=hvTtRCqC}; calico1 to cluster
2015-08-25 08:41:54,663 INFO  Adding first node EtcdClusterImpl{id=Fsa4HRJC}: EtcdNodeImpl{id=hvTtRCqC}; calico1 to cluster
2015-08-25 08:41:54,751 INFO  Starting CalicoNodeImpl{id=MCZP7WJx} on machine SshMachineLocation[ec2-54-196-17-21.compute-1.amazonaws.com:ec2-54-196-17-21.compute-1.amazonaws.com/54.196.17.21:22@MPQ0lxj1]
2015-08-25 08:41:57,875 WARN  Configuration being made to SshMachineLocation[ec2-54-196-17-21.compute-1.amazonaws.com:ec2-54-196-17-21.compute-1.amazonaws.com/54.196.17.21:22@MPQ0lxj1] after deployment; may not be supported in future versions
2015-08-25 08:42:07,175 INFO  Launching first calico service at 54.196.17.21
2015-08-25 08:42:07,995 WARN  Execution failed, invalid result 1 for launching CalicoNodeImpl{id=MCZP7WJx} (throwing)
2015-08-25 08:42:07,995 INFO  STDERR of problem in Task[ssh: launching CalicoNodeImpl{id=MCZP7WJx}:Y9JX3jEB]:
WARNING: ipv6 forwarding is not enabled.

2015-08-25 08:42:07,995 INFO  STDOUT of problem in Task[ssh: launching CalicoNodeImpl{id=MCZP7WJx}:Y9JX3jEB]:
Unable to run docker commands. Is the docker daemon running?
Executed /tmp/brooklyn-20150825-084207177-DVx7-launching_CalicoNodeImpl_id_MC.sh, result 1

2015-08-25 08:42:07,995 INFO  STDIN of problem in Task[ssh: launching CalicoNodeImpl{id=MCZP7WJx}:Y9JX3jEB]:
export RUN_DIR="/home/users/bitsofinfo.dog/brooklyn-managed-processes/apps/YhD6Amqj/entities/CalicoNode_MCZP7WJx"
mkdir -p $RUN_DIR
cd $RUN_DIR
( if test "$UID" -eq 0; then ( /home/users/bitsofinfo.dog/brooklyn-managed-processes/installs/CalicoNode_0.4.8/calicoctl node --ip=54.196.17.21 ); else sudo -E -n -S -- /home/users/bitsofinfo.dog/brooklyn-managed-processes/installs/CalicoNode_0.4.8/calicoctl node --ip=54.196.17.21; fi )
2015-08-25 08:42:08,001 WARN  Setting BasicGroupImpl{id=lIhe6lD5} on-fire due to problems when expected null / up=true: {service-lifecycle-indicators-from-children-and-members=Required entity not healthy: CalicoNodeImpl{id=MCZP7WJx}}
2015-08-25 08:42:08,001 WARN  Error invoking start at CalicoNodeImpl{id=MCZP7WJx}: Execution failed, invalid result 1 for launching CalicoNodeImpl{id=MCZP7WJx}
2015-08-25 08:42:08,006 WARN  Error processing subscriptions to LSM.publish(DockerHostImpl{id=HJIQXtop}.Sensor: service.isUp (java.lang.Boolean)=true @ 1440506507995): brooklyn.util.exceptions.PropagatedRuntimeException: Error invoking start at CalicoNodeImpl{id=MCZP7WJx}: Execution failed, invalid result 1 for launching CalicoNodeImpl{id=MCZP7WJx}
brooklyn.util.exceptions.PropagatedRuntimeException:
	at brooklyn.util.exceptions.Exceptions.propagate(Exceptions.java:97) ~[brooklyn-utils-common-0.8.0-SNAPSHOT.jar:0.8.0-SNAPSHOT]
Caused by: java.util.concurrent.ExecutionException: brooklyn.util.exceptions.PropagatedRuntimeException: Error invoking start at CalicoNodeImpl{id=MCZP7WJx}: Execution failed, invalid result 1 for launching CalicoNodeImpl{id=MCZP7WJx}
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) [na:1.8.0_45]
Caused by: brooklyn.util.exceptions.PropagatedRuntimeException: Error invoking start at CalicoNodeImpl{id=MCZP7WJx}
	at org.apache.brooklyn.core.management.internal.EffectorUtils.handleEffectorException(EffectorUtils.java:270) ~[brooklyn-core-0.8.0-SNAPSHOT.jar:0.8.0-SNAPSHOT]
Caused by: brooklyn.util.exceptions.PropagatedRuntimeException:
	at brooklyn.util.exceptions.Exceptions.propagate(Exceptions.java:97) ~[brooklyn-utils-common-0.8.0-SNAPSHOT.jar:0.8.0-SNAPSHOT]
Caused by: java.util.concurrent.ExecutionException: brooklyn.util.exceptions.PropagatedRuntimeException: Execution failed, invalid result 1 for launching CalicoNodeImpl{id=MCZP7WJx}
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) [na:1.8.0_45]
Caused by: brooklyn.util.exceptions.PropagatedRuntimeException:
	at brooklyn.util.exceptions.Exceptions.propagate(Exceptions.java:97) ~[brooklyn-utils-common-0.8.0-SNAPSHOT.jar:0.8.0-SNAPSHOT]
Caused by: java.util.concurrent.ExecutionException: brooklyn.util.exceptions.PropagatedRuntimeException: Execution failed, invalid result 1 for launching CalicoNodeImpl{id=MCZP7WJx}
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) [na:1.8.0_45]
Caused by: brooklyn.util.exceptions.PropagatedRuntimeException:
	at brooklyn.util.exceptions.Exceptions.propagate(Exceptions.java:97) ~[brooklyn-utils-common-0.8.0-SNAPSHOT.jar:0.8.0-SNAPSHOT]
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Execution failed, invalid result 1 for launching CalicoNodeImpl{id=MCZP7WJx}
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) [na:1.8.0_45]
Caused by: java.lang.IllegalStateException: Execution failed, invalid result 1 for launching CalicoNodeImpl{id=MCZP7WJx}
	at brooklyn.entity.basic.lifecycle.ScriptHelper.logWithDetailsAndThrow(ScriptHelper.java:389) ~[brooklyn-software-base-0.8.0-SNAPSHOT.jar:0.8.0-SNAPSHOT]
2015-08-25 08:42:50,324 WARN  Task[post-launch:R5cZnevq] was never submitted; did the code create it and forget to run it? ('cancel' the task to suppress this message)
2015-08-25 08:42:50,324 WARN  Task[post-start:QkNSHb79] was never submitted; did the code create it and forget to run it? ('cancel' the task to suppress this message)
2015-08-25 08:56:43,841 WARN  Software process entity DockerHostImpl{id=kcC53vSs} did not pass is-running check within the required 15m limit (15m 1s elapsed) (throwing)
2015-08-25 08:56:44,045 WARN  Service is not up when setting running on DockerHostImpl{id=kcC53vSs}; delayed 203ms but Sensor: service.isUp (java.lang.Boolean) did not recover from false; not-up-indicators={service.process.isRunning=No information on whether this service is running}
2015-08-25 08:56:44,045 WARN  Setting DockerHostImpl{id=kcC53vSs} on-fire due to problems when expected running, up=false, not-up-indicators: {service.process.isRunning=No information on whether this service is running}
2015-08-25 08:56:44,045 WARN  Setting DockerHostImpl{id=kcC53vSs} on-fire due to problems when expected running, up=false, not-up-indicators: {service.process.isRunning=No information on whether this service is running}
2015-08-25 08:56:44,047 WARN  Error invoking start at DockerHostImpl{id=kcC53vSs}: Software process entity DockerHostImpl{id=kcC53vSs} did not pass is-running check within the required 15m limit (15m 1s elapsed)
```

**Comment by bitsofinfo** [comment]
Also tried w/ the latest snapshot, against ec2 similar results

**Comment by grkvlt** [comment]
This is probably a known issue and will be because the Ubuntu image it is using is failing to upgrade the kernel. I am going to push an update with the 15.04 image shortly, I think that will fix things for you. Have been testing it today, seems to work on AWS
