### ISSUE TITLE
Clocker stop failed

### ISSUE THREAD

**Issue by sjcorbett** [brooklyncentral/clocker#151]
When stopping the application described in #150.

An invocation of the Stop effector on the Docker Cloud application failed with root cause a failure to stop one of the EtcdNodes (which had failed earlier in the deployment).

```
org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: Error invoking stop at BasicApplicationImpl{id=TaYgZIK2}: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: Error invoking stop at DockerInfrastructureImpl{id=xJiaRrBc}: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: Error invoking stop at CalicoNetworkImpl{id=pGSGOteZ}: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: Error invoking stop at EtcdClusterImpl{id=Gk58FaAu}: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: 1 of 3 parallel child tasks failed: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: Error invoking stop at EtcdNodeImpl{id=f71iRD6T}: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: java.lang.IllegalStateException: Execution failed, invalid result 1 for removeMember EtcdNodeImpl{id=f71iRD6T}
```

The exact problem was:
```
Failed after 9.76s: Error invoking stop at EtcdNodeImpl{id=f71iRD6T}: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: java.lang.IllegalStateException: Execution failed, invalid result 1 for removeMember EtcdNodeImpl{id=f71iRD6T}

Caused by: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: java.lang.IllegalStateException: Execution failed, invalid result 1 for removeMember EtcdNodeImpl{id=f71iRD6T}
	at org.apache.brooklyn.util.exceptions.Exceptions.propagate(Exceptions.java:102)
	at org.apache.brooklyn.util.core.task.BasicTask.getUnchecked(BasicTask.java:353)
	at org.apache.brooklyn.entity.software.base.lifecycle.ScriptHelper.execute(ScriptHelper.java:337)
	at brooklyn.entity.nosql.etcd.EtcdNodeSshDriver.leaveCluster(EtcdNodeSshDriver.java:221)
	at brooklyn.entity.nosql.etcd.EtcdNodeSshDriver.stop(EtcdNodeSshDriver.java:151)
	at org.apache.brooklyn.entity.software.base.SoftwareProcessDriverLifecycleEffectorTasks.stopProcessesAtMachine(SoftwareProcessDriverLifecycleEffectorTasks.java:232)
	at org.apache.brooklyn.entity.software.base.lifecycle.MachineLifecycleEffectorTasks$StopProcessesAtMachineTask.call(MachineLifecycleEffectorTasks.java:771)
	at org.apache.brooklyn.entity.software.base.lifecycle.MachineLifecycleEffectorTasks$StopProcessesAtMachineTask.call(MachineLifecycleEffectorTasks.java:768)
	... 6 more
```

I had to get into the debug log to find the output from the stop commands:

```
2015-09-08 14:52:25,158 WARN  o.a.b.e.s.b.l.ScriptHelper [brooklyn-execmanager-YbH392t6-5227]: Execution failed, invalid result 1 for removeMember EtcdNodeImpl{id=f71iRD6T} (throwing)
2015-09-08 14:52:25,159 INFO  o.a.b.e.s.b.l.ScriptHelper [brooklyn-execmanager-YbH392t6-5227]: STDERR of problem in Task[ssh: removeMember EtcdNodeImpl{id=f71iRD6T}:uML2O0pH]:
Recieved an error trying to remove member 8e21d999ac31510d: context deadline exceeded

2015-09-08 14:52:25,159 INFO  o.a.b.e.s.b.l.ScriptHelper [brooklyn-execmanager-YbH392t6-5227]: STDOUT of problem in Task[ssh: removeMember EtcdNodeImpl{id=f71iRD6T}:uML2O0pH]:
Executed /tmp/brooklyn-20150908-145217770-pIs7-removeMember_EtcdNodeImpl_id_f.sh, result 1

2015-09-08 14:52:25,159 INFO  o.a.b.e.s.b.l.ScriptHelper [brooklyn-execmanager-YbH392t6-5227]: STDIN of problem in Task[ssh: removeMember EtcdNodeImpl{id=f71iRD6T}:uML2O0pH]:
cd /home/users/brooklyn/brooklyn-managed-processes/apps/TaYgZIK2/entities/EtcdNode_f71iRD6T
/home/users/brooklyn/brooklyn-managed-processes/installs/EtcdNode_2.0.11/etcd-v2.0.11-linux-amd64/etcdctl --peers http://10.235.43.152:2379 member remove 8e21d999ac31510d
```
DockerHosts were stopped as expected.

**Comment by grkvlt** [comment]
I think I need to serialise the `EtcdNode` shutdown with a lock to prevent this race. *OR* we could just ignore exceprions on shutdown?

**Comment by grkvlt** [comment]
Fixed by adding locking
