### ISSUE TITLE
riak deploy fails: duplicate security group rule

### ISSUE THREAD

**Issue by aledsage** [brooklyncentral/clocker#169]
Using release Version 1.1.0-PREVIEW.20151005, I launched clocker+weave in AWS. I then deployed the out-of-the-box riak app (twice).

In the second attempt, the HAProxyController entity failed with error shown below.

```
Failed after 14.6s: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: Error invoking start at DockerContainerImpl{id=Ev9jaqdj}: java.lang.RuntimeException: Unable to add security group rule; repeated errors from provider: Unable to add security group rule; repeated errors from provider: The permission '0.0.0.0/0-tcp-8000-8000' has already been authorized on the specified group: org.jclouds.aws.AWSResponseException: request POST https://ec2.us-east-1.amazonaws.com/ HTTP/1.1 failed with code 400, error: AWSError{requestId='e177c0f9-bda1-46f7-adf5-185fc68331cb', requestToken='null', code='InvalidPermission.Duplicate', message='The permission '0.0.0.0/0-tcp-8000-8000' has already been authorized on the specified group', context='{Response=, Errors=}'}

org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: Error invoking start at DockerContainerImpl{id=Ev9jaqdj}: java.lang.RuntimeException: Unable to add security group rule; repeated errors from provider: Unable to add security group rule; repeated errors from provider: The permission '0.0.0.0/0-tcp-8000-8000' has already been authorized on the specified group: org.jclouds.aws.AWSResponseException: request POST https://ec2.us-east-1.amazonaws.com/ HTTP/1.1 failed with code 400, error: AWSError{requestId='e177c0f9-bda1-46f7-adf5-185fc68331cb', requestToken='null', code='InvalidPermission.Duplicate', message='The permission '0.0.0.0/0-tcp-8000-8000' has already been authorized on the specified group', context='{Response=, Errors=}'}
	at org.apache.brooklyn.util.exceptions.Exceptions.propagate(Exceptions.java:102)
	at org.apache.brooklyn.util.core.task.BasicTask.getUnchecked(BasicTask.java:353)
	at brooklyn.location.docker.DockerHostLocation.obtain(DockerHostLocation.java:233)
	at brooklyn.location.docker.DockerLocation.obtain(DockerLocation.java:189)
	at org.apache.brooklyn.entity.software.base.lifecycle.MachineLifecycleEffectorTasks$ObtainLocationTask.call(MachineLifecycleEffectorTasks.java:404)
	at org.apache.brooklyn.entity.software.base.lifecycle.MachineLifecycleEffectorTasks$ObtainLocationTask.call(MachineLifecycleEffectorTasks.java:394)
	at org.apache.brooklyn.util.core.task.Tasks.withBlockingDetails(Tasks.java:98)
	at org.apache.brooklyn.entity.software.base.lifecycle.MachineLifecycleEffectorTasks$ProvisionMachineTask.call(MachineLifecycleEffectorTasks.java:378)
	at org.apache.brooklyn.entity.software.base.lifecycle.MachineLifecycleEffectorTasks$ProvisionMachineTask.call(MachineLifecycleEffectorTasks.java:362)
	at org.apache.brooklyn.util.core.task.DynamicSequentialTask$DstJob.call(DynamicSequentialTask.java:342)
	at org.apache.brooklyn.util.core.task.BasicExecutionManager$SubmissionCallable.call(BasicExecutionManager.java:468)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: Error invoking start at DockerContainerImpl{id=Ev9jaqdj}: java.lang.RuntimeException: Unable to add security group rule; repeated errors from provider: Unable to add security group rule; repeated errors from provider: The permission '0.0.0.0/0-tcp-8000-8000' has already been authorized on the specified group: org.jclouds.aws.AWSResponseException: request POST https://ec2.us-east-1.amazonaws.com/ HTTP/1.1 failed with code 400, error: AWSError{requestId='e177c0f9-bda1-46f7-adf5-185fc68331cb', requestToken='null', code='InvalidPermission.Duplicate', message='The permission '0.0.0.0/0-tcp-8000-8000' has already been authorized on the specified group', context='{Response=, Errors=}'}
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:63)
	at org.apache.brooklyn.util.core.task.BasicTask.get(BasicTask.java:342)
	at org.apache.brooklyn.util.core.task.BasicTask.getUnchecked(BasicTask.java:351)
	... 13 more
Caused by: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: Error invoking start at DockerContainerImpl{id=Ev9jaqdj}: java.lang.RuntimeException: Unable to add security group rule; repeated errors from provider: Unable to add security group rule; repeated errors from provider: The permission '0.0.0.0/0-tcp-8000-8000' has already been authorized on the specified group: org.jclouds.aws.AWSResponseException: request POST https://ec2.us-east-1.amazonaws.com/ HTTP/1.1 failed with code 400, error: AWSError{requestId='e177c0f9-bda1-46f7-adf5-185fc68331cb', requestToken='null', code='InvalidPermission.Duplicate', message='The permission '0.0.0.0/0-tcp-8000-8000' has already been authorized on the specified group', context='{Response=, Errors=}'}
	at org.apache.brooklyn.util.exceptions.Exceptions.propagate(Exceptions.java:102)
	at org.apache.brooklyn.util.core.task.BasicTask.getUnchecked(BasicTask.java:353)
	at org.apache.brooklyn.util.core.task.DynamicTasks.get(DynamicTasks.java:294)
	at org.apache.brooklyn.util.core.task.BasicExecutionContext$1.call(BasicExecutionContext.java:138)
	... 6 more
Caused by: java.util.concurrent.ExecutionException: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: Error invoking start at DockerContainerImpl{id=Ev9jaqdj}: java.lang.RuntimeException: Unable to add security group rule; repeated errors from provider: Unable to add security group rule; repeated errors from provider: The permission '0.0.0.0/0-tcp-8000-8000' has already been authorized on the specified group: org.jclouds.aws.AWSResponseException: request POST https://ec2.us-east-1.amazonaws.com/ HTTP/1.1 failed with code 400, error: AWSError{requestId='e177c0f9-bda1-46f7-adf5-185fc68331cb', requestToken='null', code='InvalidPermission.Duplicate', message='The permission '0.0.0.0/0-tcp-8000-8000' has already been authorized on the specified group', context='{Response=, Errors=}'}
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:63)
	at org.apache.brooklyn.util.core.task.BasicTask.get(BasicTask.java:342)
	at org.apache.brooklyn.util.core.task.BasicTask.getUnchecked(BasicTask.java:351)
	... 8 more
Caused by: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: Error invoking start at DockerContainerImpl{id=Ev9jaqdj}: java.lang.RuntimeException: Unable to add security group rule; repeated errors from provider: Unable to add security group rule; repeated errors from provider: The permission '0.0.0.0/0-tcp-8000-8000' has already been authorized on the specified group: org.jclouds.aws.AWSResponseException: request POST https://ec2.us-east-1.amazonaws.com/ HTTP/1.1 failed with code 400, error: AWSError{requestId='e177c0f9-bda1-46f7-adf5-185fc68331cb', requestToken='null', code='InvalidPermission.Duplicate', message='The permission '0.0.0.0/0-tcp-8000-8000' has already been authorized on the specified group', context='{Response=, Errors=}'}
	at org.apache.brooklyn.core.mgmt.internal.EffectorUtils.handleEffectorException(EffectorUtils.java:269)
	at org.apache.brooklyn.core.mgmt.internal.EffectorUtils.invokeMethodEffector(EffectorUtils.java:254)
	at org.apache.brooklyn.core.effector.MethodEffector.call(MethodEffector.java:149)
	at org.apache.brooklyn.core.entity.trait.Startable$StartEffectorBody.call(Startable.java:56)
	at org.apache.brooklyn.core.entity.trait.Startable$StartEffectorBody.call(Startable.java:50)
	at org.apache.brooklyn.core.effector.EffectorTasks$EffectorBodyTaskFactory$1.call(EffectorTasks.java:82)
	... 6 more
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unable to add security group rule; repeated errors from provider
	at org.apache.brooklyn.core.mgmt.internal.AbstractManagementContext.invokeEffectorMethodSync(AbstractManagementContext.java:316)
	at org.apache.brooklyn.core.mgmt.internal.EffectorUtils.invokeMethodEffector(EffectorUtils.java:249)
	... 10 more
Caused by: java.lang.RuntimeException: Unable to add security group rule; repeated errors from provider
	at org.apache.brooklyn.location.jclouds.networking.JcloudsLocationSecurityGroupCustomizer.runOperationWithRetry(JcloudsLocationSecurityGroupCustomizer.java:514)
	at org.apache.brooklyn.location.jclouds.networking.JcloudsLocationSecurityGroupCustomizer.addPermission(JcloudsLocationSecurityGroupCustomizer.java:460)
	at org.apache.brooklyn.location.jclouds.networking.JcloudsLocationSecurityGroupCustomizer.addPermissionsToLocation(JcloudsLocationSecurityGroupCustomizer.java:238)
	at org.apache.brooklyn.location.jclouds.networking.JcloudsLocationSecurityGroupCustomizer.addPermissionsToLocation(JcloudsLocationSecurityGroupCustomizer.java:192)
	at brooklyn.entity.container.docker.DockerHostImpl.addIpPermissions(DockerHostImpl.java:547)
	at brooklyn.entity.container.docker.DockerContainerImpl.configurePortBindings(DockerContainerImpl.java:497)
	at brooklyn.entity.container.docker.DockerContainerImpl.createLocation(DockerContainerImpl.java:540)
	at brooklyn.entity.container.docker.DockerContainerImpl.start(DockerContainerImpl.java:667)
	at sun.reflect.GeneratedMethodAccessor59.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1085)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:149)
	at groovy.lang.MetaObjectProtocol$invokeMethod.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at groovy.lang.MetaObjectProtocol$invokeMethod.call(Unknown Source)
	at org.apache.brooklyn.util.groovy.GroovyJavaMethods.invokeMethodOnMetaClass(GroovyJavaMethods.groovy:144)
	at org.apache.brooklyn.core.mgmt.internal.AbstractManagementContext.invokeEffectorMethodLocal(AbstractManagementContext.java:288)
	at org.apache.brooklyn.core.mgmt.internal.AbstractManagementContext.invokeEffectorMethodSync(AbstractManagementContext.java:312)
	... 11 more
Caused by: java.lang.IllegalStateException: The permission '0.0.0.0/0-tcp-8000-8000' has already been authorized on the specified group
	at org.jclouds.aws.handlers.ParseAWSErrorFromXmlContent.refineException(ParseAWSErrorFromXmlContent.java:113)
	at org.jclouds.aws.handlers.ParseAWSErrorFromXmlContent.handleError(ParseAWSErrorFromXmlContent.java:89)
	at org.jclouds.http.handlers.DelegatingErrorHandler.handleError(DelegatingErrorHandler.java:65)
	at org.jclouds.http.internal.BaseHttpCommandExecutorService.shouldContinue(BaseHttpCommandExecutorService.java:136)
	at org.jclouds.http.internal.BaseHttpCommandExecutorService.invoke(BaseHttpCommandExecutorService.java:105)
	at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:90)
	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:73)
	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:44)
	at org.jclouds.reflect.FunctionalReflection$FunctionalInvocationHandler.handleInvocation(FunctionalReflection.java:117)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy155.authorizeSecurityGroupIngressInRegion(Unknown Source)
	at org.jclouds.aws.ec2.compute.extensions.AWSEC2SecurityGroupExtension.addIpPermission(AWSEC2SecurityGroupExtension.java:121)
	at org.apache.brooklyn.location.jclouds.networking.JcloudsLocationSecurityGroupCustomizer$8.call(JcloudsLocationSecurityGroupCustomizer.java:457)
	at org.apache.brooklyn.location.jclouds.networking.JcloudsLocationSecurityGroupCustomizer$8.call(JcloudsLocationSecurityGroupCustomizer.java:454)
	at org.apache.brooklyn.location.jclouds.networking.JcloudsLocationSecurityGroupCustomizer.runOperationWithRetry(JcloudsLocationSecurityGroupCustomizer.java:497)
	... 32 more
Caused by: org.jclouds.aws.AWSResponseException: request POST https://ec2.us-east-1.amazonaws.com/ HTTP/1.1 failed with code 400, error: AWSError{requestId='e177c0f9-bda1-46f7-adf5-185fc68331cb', requestToken='null', code='InvalidPermission.Duplicate', message='The permission '0.0.0.0/0-tcp-8000-8000' has already been authorized on the specified group', context='{Response=, Errors=}'}
	at org.jclouds.aws.handlers.ParseAWSErrorFromXmlContent.handleError(ParseAWSErrorFromXmlContent.java:75)
	... 45 more
```

**Comment by aledsage** [comment]
It looks like a fix for this has already been made in Apache Brooklyn: https://github.com/apache/incubator-brooklyn/commit/4096358f5fcc3058f8185d2587086d93fb023c9a

**Comment by grkvlt** [comment]
I'll check whether pulling that commit into `patches` solves the problem, as an interim fix. Obviously the best fix is to update the dependency version for Brooklyn, which we will do when there is a new stable release.

**Comment by aledsage** [comment]
Actually, that commit isn't enough: I still got the error using the latest Apache Brooklyn 0.9.0-SNAPSHOT (commit 49eabd157c4f2183e26800840b55bd0c537dcaa3).

I'm testing again with this hacky fix in `JcloudsLocationSecurityGroupCustomizer`. It seems to fix it, but then I hit another problem that I'll put in a separate issue:

```
    protected SecurityGroup addPermission(final IpPermission permission, final SecurityGroup group, final SecurityGroupExtension securityApi) {
        LOG.debug("Adding permission to security group {}: {}", group.getName(), permission);
        Callable<SecurityGroup> callable = new Callable<SecurityGroup>() {
            @Override
            public SecurityGroup call() throws Exception {
                try {
                    return securityApi.addIpPermission(permission, group);
                } catch (AWSResponseException e) {
                    if ("InvalidPermission.Duplicate".equals(e.getError().getCode())) {
                        // already exists
                        LOG.info("Permission already exists for security group; continuing (logging underlying exception at debug): permission="+permission+"; group="+group);
                        LOG.debug("Permission already exists for security group; continuing: permission="+permission+"; group="+group, e);
                        return null;
                    } else {
                        throw e;
                    }
                } catch (Exception e) {
                    Exceptions.propagateIfFatal(e);
                    if (e.toString().contains("InvalidPermission.Duplicate")) {
                        // belt-and-braces, in case 
                        // already exists
                        LOG.info("Permission already exists for security group; continuing (but unexpected exception type): permission="+permission+"; group="+group, e);
                        return null;
                    } else {
                        throw Exceptions.propagate(e);
                    }
                }
            }
        };
        return runOperationWithRetry(callable);
    }
```

**Comment by grkvlt** [comment]
OK, I'm confused. That commit was by me, and it *is* in Clocker... Clocker also has extra locking to deal with the fact that there is an obvious TOCTTOU race, but your fix is probably a good defensive mechanism for the cases we can't catch with in-process locking.
