### ISSUE TITLE
HAProxyController fails: "UnsupportedOperationException: Driver expected to be used in a container with HAProxy installed"

### ISSUE THREAD

**Issue by aledsage** [brooklyncentral/clocker#174]
Deploying the riak+web clusters app to a Clocker in AWS, the HAProxyController failed with the error `UnsupportedOperationException: Driver expected to be used in a container with HAProxy installed`.

This is with running against Brooklyn 0.9.0-SNAPSHOT.

My guess is that it's related to the patched classes in clocker, given that we get the exception in the old-named `brooklyn.entity.proxy.haproxy.HAProxySshDriver.install`.

```
Failed after 8m 8s: Error invoking start at HAProxyControllerImpl{id=PxrLWkuI}: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: java.lang.UnsupportedOperationException: Driver expected to be used in a container with HAProxy installed

org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: Error invoking start at HAProxyControllerImpl{id=PxrLWkuI}: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: java.lang.UnsupportedOperationException: Driver expected to be used in a container with HAProxy installed
	at org.apache.brooklyn.core.mgmt.internal.EffectorUtils.handleEffectorException(EffectorUtils.java:270)
	at org.apache.brooklyn.core.effector.EffectorTasks$EffectorBodyTaskFactory$2.handleException(EffectorTasks.java:90)
	at org.apache.brooklyn.util.core.task.DynamicSequentialTask.handleException(DynamicSequentialTask.java:452)
	at org.apache.brooklyn.util.core.task.DynamicSequentialTask$DstJob.call(DynamicSequentialTask.java:400)
	at org.apache.brooklyn.util.core.task.BasicExecutionManager$SubmissionCallable.call(BasicExecutionManager.java:468)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: java.lang.UnsupportedOperationException: Driver expected to be used in a container with HAProxy installed
	at org.apache.brooklyn.util.exceptions.Exceptions.propagate(Exceptions.java:103)
	at org.apache.brooklyn.util.core.task.BasicTask.getUnchecked(BasicTask.java:353)
	at org.apache.brooklyn.util.core.task.DynamicSequentialTask.drain(DynamicSequentialTask.java:475)
	at org.apache.brooklyn.util.core.task.DynamicTasks.drain(DynamicTasks.java:313)
	at org.apache.brooklyn.util.core.task.DynamicTasks.waitForLast(DynamicTasks.java:302)
	at org.apache.brooklyn.entity.software.base.lifecycle.MachineLifecycleEffectorTasks.start(MachineLifecycleEffectorTasks.java:314)
	at org.apache.brooklyn.entity.software.base.lifecycle.MachineLifecycleEffectorTasks$StartEffectorBody.call(MachineLifecycleEffectorTasks.java:214)
	at org.apache.brooklyn.entity.software.base.lifecycle.MachineLifecycleEffectorTasks$StartEffectorBody.call(MachineLifecycleEffectorTasks.java:201)
	at org.apache.brooklyn.core.effector.EffectorTasks$EffectorBodyTaskFactory$1.call(EffectorTasks.java:82)
	at org.apache.brooklyn.util.core.task.DynamicSequentialTask$DstJob.call(DynamicSequentialTask.java:342)
	... 5 more
Caused by: java.util.concurrent.ExecutionException: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: java.lang.UnsupportedOperationException: Driver expected to be used in a container with HAProxy installed
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:63)
	at org.apache.brooklyn.util.core.task.BasicTask.get(BasicTask.java:342)
	at org.apache.brooklyn.util.core.task.BasicTask.getUnchecked(BasicTask.java:351)
	... 13 more
Caused by: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: java.lang.UnsupportedOperationException: Driver expected to be used in a container with HAProxy installed
	at org.apache.brooklyn.util.exceptions.Exceptions.propagate(Exceptions.java:103)
	at org.apache.brooklyn.util.core.task.BasicTask.getUnchecked(BasicTask.java:353)
	at org.apache.brooklyn.util.core.task.DynamicSequentialTask.drain(DynamicSequentialTask.java:475)
	at org.apache.brooklyn.util.core.task.DynamicTasks.drain(DynamicTasks.java:313)
	at org.apache.brooklyn.util.core.task.DynamicTasks.waitForLast(DynamicTasks.java:302)
	at org.apache.brooklyn.util.core.task.DynamicSequentialTask$DstJob.call(DynamicSequentialTask.java:383)
	... 5 more
Caused by: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: Driver expected to be used in a container with HAProxy installed
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:63)
	at org.apache.brooklyn.util.core.task.BasicTask.get(BasicTask.java:342)
	at org.apache.brooklyn.util.core.task.BasicTask.getUnchecked(BasicTask.java:351)
	... 9 more
Caused by: java.lang.UnsupportedOperationException: Driver expected to be used in a container with HAProxy installed
	at brooklyn.entity.proxy.haproxy.HAProxySshDriver.install(HAProxySshDriver.java:46)
	at org.apache.brooklyn.entity.software.base.AbstractSoftwareProcessDriver$6.run(AbstractSoftwareProcessDriver.java:139)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at org.apache.brooklyn.util.core.task.DynamicSequentialTask$DstJob.call(DynamicSequentialTask.java:342)
	... 5 more
```

**Comment by aledsage** [comment]
This is non-deterministic. It has worked about 5 times out of 6 when run against a fresh clocker. This is the first time I've seen this error.

**Comment by grkvlt** [comment]
This blueprint will never work on AWS because the HAProxy entity uses a Docker image and has no non-Docker driver. Should be documented more clearly, I think.

**Comment by grkvlt** [comment]
Although I assigned _wontfix_ status, I suppoose we could be nicer in Brooklyn (and Clocker) about error reporting and the types of locations entities want. I think the best way to fix this is to fail early with an `IllegalStateException` or even an `UnsupportedLocationException`?

**Comment by grkvlt** [comment]
Duplicate of #171

**Comment by grkvlt** [comment]
@googlielmo is fixing the blueprints to make them work on both Cloud VMs and Docker/Marathon.
