### ISSUE TITLE
App fails to deploy when container name already in use

### ISSUE THREAD

**Issue by johnmccabe** [brooklyncentral/clocker#200]
Deploying the `redis`/`dnmonster` example from the getting started instructuctions followed by the `nodejs-demo-application` app from the catalog results in the following error due to a clash with `redis` container name already being in use.

Should probably dynamically allocation container names to avoid such clashes.

```
2015-11-26 17:42:23,900 WARN  Error invoking start at BasicApplicationImpl{id=D6Q65ORZ}: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: org.apache.brooklyn.util.exceptions.CompoundRuntimeException: 2 of 2 parallel child tasks failed, 2 errors including: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: Error invoking start at RedisStoreImpl{id=bpIaGJKg}: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: Error invoking start at DockerContainerImpl{id=hYDjS28T}: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: org.jclouds.compute.RunNodesException: error running 1 node group(brooklyn-nyfnu3-johnmccabe) location(docker) image(2ef3e471ffcbca40f37386e820d0b539139b38ae37047ddebc4b0f532c511d7b) size(small) options(DockerTemplateOptions{dns=[], hostname=redis, memory=null, cpuShares=null, entrypoint=null, commands=null, volumes={}, env=[], portBindings={}, extraHosts={}})
Execution failures:

1) ExecutionException on redis:
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Conflict. The name "redis" is already in use by container 4e0d3b4f4d84. You have to delete (or rename) that container to be able to reuse that name.

        at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
        at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
        at org.jclouds.concurrent.FutureIterables$1.run(FutureIterables.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Conflict. The name "redis" is already in use by container 4e0d3b4f4d84. You have to delete (or rename) that container to be able to reuse that name.

        at org.jclouds.docker.handlers.DockerErrorHandler.handleError(DockerErrorHandler.java:80)
        at org.jclouds.http.handlers.DelegatingErrorHandler.handleError(DelegatingErrorHandler.java:65)
        at org.jclouds.http.internal.BaseHttpCommandExecutorService.shouldContinue(BaseHttpCommandExecutorService.java:136)
        at org.jclouds.http.internal.BaseHttpCommandExecutorService.invoke(BaseHttpCommandExecutorService.java:105)
        at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:90)
        at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:73)
        at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:44)
        at org.jclouds.reflect.FunctionalReflection$FunctionalInvocationHandler.handleInvocation(FunctionalReflection.java:117)
        at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
        at com.sun.proxy.$Proxy178.createContainer(Unknown Source)
        at org.jclouds.docker.compute.strategy.DockerComputeServiceAdapter.createNodeWithGroupEncodedIntoName(DockerComputeServiceAdapter.java:118)
        at org.jclouds.compute.strategy.impl.AdaptingComputeServiceStrategies.createNodeWithGroupEncodedIntoName(AdaptingComputeServiceStrategies.java:195)
        at org.jclouds.compute.strategy.impl.CreateNodesWithGroupEncodedIntoNameThenAddToSet$AddNode.call(CreateNodesWithGroupEncodedIntoNameThenAddToSet.java:79)
        at org.jclouds.compute.strategy.impl.CreateNodesWithGroupEncodedIntoNameThenAddToSet$AddNode.call(CreateNodesWithGroupEncodedIntoNameThenAddToSet.java:63)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
        at java.lang.Thread.getStackTrace(Thread.java:1552)
        at org.jclouds.compute.strategy.impl.CreateNodesWithGroupEncodedIntoNameThenAddToSet.createNodeInGroupWithNameAndTemplate(CreateNodesWithGroupEncodedIntoNameThenAddToSet.java:167)
        at org.jclouds.compute.strategy.impl.CreateNodesWithGroupEncodedIntoNameThenAddToSet.execute(CreateNodesWithGroupEncodedIntoNameThenAddToSet.java:122)
        at org.jclouds.compute.internal.BaseComputeService.createNodesInGroup(BaseComputeService.java:210)
        at org.apache.brooklyn.location.jclouds.JcloudsLocation.obtainOnce(JcloudsLocation.java:719)
        at org.apache.brooklyn.location.jclouds.JcloudsLocation.obtain(JcloudsLocation.java:609)
        at brooklyn.entity.container.docker.DockerContainerImpl.createLocation(DockerContainerImpl.java:576)
        at brooklyn.entity.container.docker.DockerContainerImpl.start(DockerContainerImpl.java:672)
        at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:149)
        at groovy.lang.MetaObjectProtocol$invokeMethod.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at groovy.lang.MetaObjectProtocol$invokeMethod.call(Unknown Source)
        at org.apache.brooklyn.util.groovy.GroovyJavaMethods.invokeMethodOnMetaClass(GroovyJavaMethods.java:191)
        at org.apache.brooklyn.core.mgmt.internal.AbstractManagementContext.invokeEffectorMethodLocal(AbstractManagementContext.java:309)
        at org.apache.brooklyn.core.mgmt.internal.AbstractManagementContext.invokeEffectorMethodSync(AbstractManagementContext.java:333)
        at org.apache.brooklyn.core.mgmt.internal.EffectorUtils.invokeMethodEffector(EffectorUtils.java:250)
        at org.apache.brooklyn.core.effector.MethodEffector.call(MethodEffector.java:149)
        at org.apache.brooklyn.core.entity.trait.Startable$StartEffectorBody.call(Startable.java:56)
        at org.apache.brooklyn.core.entity.trait.Startable$StartEffectorBody.call(Startable.java:50)
        at org.apache.brooklyn.core.effector.EffectorTasks$EffectorBodyTaskFactory$1.call(EffectorTasks.java:82)
        at org.apache.brooklyn.util.core.task.DynamicSequentialTask$DstJob.call(DynamicSequentialTask.java:342)
        at org.apache.brooklyn.util.core.task.BasicExecutionManager$SubmissionCallable.call(BasicExecutionManager.java:492)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 3 more
Caused by: org.jclouds.http.HttpResponseException: command: POST http://159.8.59.240:2377/v1.16/containers/create?name=redis HTTP/1.1 failed with response: HTTP/1.1 409 Conflict; content: [Conflict. The name "redis" is already in use by container 4e0d3b4f4d84. You have to delete (or rename) that container to be able to reuse that name.
]
        at org.jclouds.docker.handlers.DockerErrorHandler.handleError(DockerErrorHandler.java:50)
        at org.jclouds.http.handlers.DelegatingErrorHandler.handleError(DelegatingErrorHandler.java:65)
        at org.jclouds.http.internal.BaseHttpCommandExecutorService.shouldContinue(BaseHttpCommandExecutorService.java:136)
        at org.jclouds.http.internal.BaseHttpCommandExecutorService.invoke(BaseHttpCommandExecutorService.java:105)
        at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:90)
        at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:73)
        at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:44)
        at org.jclouds.reflect.FunctionalReflection$FunctionalInvocationHandler.handleInvocation(FunctionalReflection.java:117)
        at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
        at com.sun.proxy.$Proxy178.createContainer(Unknown Source)
        at org.jclouds.docker.compute.strategy.DockerComputeServiceAdapter.createNodeWithGroupEncodedIntoName(DockerComputeServiceAdapter.java:118)
        at org.jclouds.compute.strategy.impl.AdaptingComputeServiceStrategies.createNodeWithGroupEncodedIntoName(AdaptingComputeServiceStrategies.java:195)
        at org.jclouds.compute.strategy.impl.CreateNodesWithGroupEncodedIntoNameThenAddToSet$AddNode.call(CreateNodesWithGroupEncodedIntoNameThenAddToSet.java:79)
        at org.jclouds.compute.strategy.impl.CreateNodesWithGroupEncodedIntoNameThenAddToSet$AddNode.call(CreateNodesWithGroupEncodedIntoNameThenAddToSet.java:63)
        ... 4 more
```

**Comment by grkvlt** [comment]
This is because both apps ask for the same container name, via the `id` of the entity. Not convinced this is a problem.

**Comment by grkvlt** [comment]
Fixed by seting container name to `camp_plan_id_xxxxxx` where _xxxxxx_ is the entity ID.
