### ISSUE TITLE
Mesos cluster not rebindable

### ISSUE THREAD

**Issue by neykov** [brooklyncentral/clocker#217]
After rebinding to an existing mesos cluster:

```
2015-12-08 14:36:18,001 INFO  Rebind MesosSlaveImpl{id=CW0QSmDq} connecting to pre-running service
2015-12-08 14:36:18,022 INFO  Rebind MesosSlaveImpl{id=TphNRHlL} connecting to pre-running service
2015-12-08 14:36:18,036 INFO  Rebind MesosSlaveImpl{id=WVYV6wRc} connecting to pre-running service
2015-12-08 14:36:18,075 INFO  Close called on Mesos cluster: MesosLocation{id=TLeBpc8E, name=Mesos Cluster q61dXBJU}
2015-12-08 14:36:18,075 INFO  Close called on Marathon framework null: MarathonLocation{id=MYXu8kXR, name=Marathon Framework, owner=null, framework=null}
2015-12-08 14:36:18,075 INFO  null: Closing Marathon framework: MarathonLocation{id=MYXu8kXR, name=Marathon Framework, owner=null, framework=null}
2015-12-08 14:36:18,077 INFO  Marathon framework closed: MarathonLocation{id=MYXu8kXR, name=Marathon Framework, owner=null, framework=null}
2015-12-08 14:36:18,137 INFO  Rebind complete (MASTER) in 2.09s: 1 app, 24 entities, 6 locations, 0 policies, 73 enrichers, 0 feeds, 81 catalog items
2015-12-08 14:36:18,278 INFO  Back-up of persisted state created on promotion, in /Users/svet/.brooklyn/brooklyn-persisted-state/backups/2015-12-08-1436-pFE71Gop-promotion-T1t1
2015-12-08 14:36:18,279 INFO  Management node pFE71Gop running as HA MASTER autodetected
2015-12-08 14:36:18,407 INFO  Launched Brooklyn; will now block until shutdown command received via GUI/API (recommended) or process interrupt.
2015-12-08 14:36:20,023 WARN  Problem connecting sensors on rebind of MesosSlaveImpl{id=CW0QSmDq}
java.lang.IllegalStateException: Cannot execute Task[ssh: Getting machine details for: SshMachineLocation[mi-2-worker-001:mi-2-worker-001/52.90.238.51:22@QEn1Htec]:HsuubaS3] without an execution context; ensure caller is in an ExecutionContext
    at org.apache.brooklyn.util.core.task.DynamicTasks$TaskQueueingResult.orSubmitInternal(DynamicTasks.java:119) ~[brooklyn-core-0.8.0-incubating.jar:0.8.0-incubating]
2015-12-08 14:36:23,976 WARN  Problem connecting sensors on rebind of MesosSlaveImpl{id=WVYV6wRc}
java.lang.IllegalStateException: Cannot execute Task[ssh: Getting machine details for: SshMachineLocation[mi-2-worker-003:mi-2-worker-003/52.91.172.11:22@ot6XgOK1]:QAwpv8w4] without an execution context; ensure caller is in an ExecutionContext
    at org.apache.brooklyn.util.core.task.DynamicTasks$TaskQueueingResult.orSubmitInternal(DynamicTasks.java:119) ~[brooklyn-core-0.8.0-incubating.jar:0.8.0-incubating]
2015-12-08 14:36:27,893 WARN  Problem connecting sensors on rebind of MesosSlaveImpl{id=TphNRHlL}
java.lang.IllegalStateException: Cannot execute Task[ssh: Getting machine details for: SshMachineLocation[mi-2-worker-002:mi-2-worker-002/54.164.45.88:22@CHNft9I1]:kDUFVhOH] without an execution context; ensure caller is in an ExecutionContext
    at org.apache.brooklyn.util.core.task.DynamicTasks$TaskQueueingResult.orSubmitInternal(DynamicTasks.java:119) ~[brooklyn-core-0.8.0-incubating.jar:0.8.0-incubating]
```

Launching a blueprint creates the container in marathon, but the task (in clocker) never completes.

**Comment by grkvlt** [comment]
@neykov There's probably something being stored in entity state that ought to be in a sensor/attribute?

**Comment by neykov** [comment]
One of the problems is with `MachineEntity` needing to ssh in to the slave machine, using `DynamicTasks` when there's no context entity (because of https://github.com/neykov/incubator-brooklyn/blob/master/software/base/src/main/java/brooklyn/entity/basic/SoftwareProcessImpl.java#L211). 
So not directly related to the mesos impl - looks like a brooklyn problem.

The close logs come from the rebind mgr location GC - https://github.com/apache/incubator-brooklyn/blob/master/core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/RebindIteration.java#L681. Not sure if legit.
