### ISSUE TITLE
NPE rebinding to clocker persisted state - causes Brooklyn server restart to fail

### ISSUE THREAD

**Issue by aledsage** [brooklyncentral/clocker#237]
When restarting Brooklyn with a couple of clocker+calico apps (as deployed from the default catalog)...

I got the `NullPointerException` shown below.

In brief, `DockerInfrastructureImpl.rebind()` calls its PROPERTIES_RELOAD_LISTENER, which `ReloadDockerLocation.reloaded()`. This tries to resolve the spec. However, the `DockerLocation` instances have not been fully rebound yet - so the call to `dockerLocation.owner()` returns null (even though it will eventually have its "owner" reset.

I suspect that if we could delay the call to the reload listener until later, then we wouldn't get this NPE.

Guarding against the NPE in `DockerResolver` is probably not a good idea - it would create an identical location, so we'd get a duplicate.

```
2016-02-21 16:50:54,434 ERROR o.a.b.l.BrooklynLauncher [main]: Subsystem for persistence had startup error (continuing with startup): org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: Failure 
rebinding: problem rebinding entity j1M7T5XG (DockerInfrastructureImpl{id=j1M7T5XG}): Cannot instantiate location 'LocationDefinition{id='gzuSFMac', name='my-docker-cloud-vagrant', spec='docker:j1M7T5XG:(name="my-docker-cloud-vagrant")', config={provisioner=FixedListMac
hineProvisioningLocation{id=DtPfBrpb, name=FixedListMachineProvisioningLocation:DtPf}, strategies=[DockerAwarePlacementStrategy(MaxContainersPlacementStrategy@j8yVexHt), DockerAwarePlacementStrategy(BreadthFirstPlacementStrategy@ce2SXY0W)]}}' pointing at docker:j1M7T5XG
:(name="my-docker-cloud-vagrant"): java.lang.NullPointerException
org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: 
        at org.apache.brooklyn.util.exceptions.Exceptions.propagate(Exceptions.java:108) ~[brooklyn-utils-common-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        at org.apache.brooklyn.core.mgmt.rebind.RebindManagerImpl.rebind(RebindManagerImpl.java:507) ~[brooklyn-core-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        at org.apache.brooklyn.core.mgmt.ha.HighAvailabilityManagerImpl.promoteToMaster(HighAvailabilityManagerImpl.java:836) ~[brooklyn-core-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        at org.apache.brooklyn.core.mgmt.ha.HighAvailabilityManagerImpl.checkMaster(HighAvailabilityManagerImpl.java:810) ~[brooklyn-core-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        at org.apache.brooklyn.core.mgmt.ha.HighAvailabilityManagerImpl.publishAndCheck(HighAvailabilityManagerImpl.java:592) ~[brooklyn-core-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        at org.apache.brooklyn.core.mgmt.ha.HighAvailabilityManagerImpl.changeMode(HighAvailabilityManagerImpl.java:315) ~[brooklyn-core-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        at org.apache.brooklyn.core.mgmt.ha.HighAvailabilityManagerImpl.start(HighAvailabilityManagerImpl.java:255) ~[brooklyn-core-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        at org.apache.brooklyn.launcher.BrooklynLauncher.startPersistence(BrooklynLauncher.java:908) ~[brooklyn-launcher-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        at org.apache.brooklyn.launcher.BrooklynLauncher.start(BrooklynLauncher.java:605) ~[brooklyn-launcher-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        at org.apache.brooklyn.cli.Main$LaunchCommand.call(Main.java:457) [brooklyn-cli-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        at org.apache.brooklyn.cli.Main$LaunchCommand.call(Main.java:194) [brooklyn-cli-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        at org.apache.brooklyn.cli.AbstractMain.execCli(AbstractMain.java:252) [brooklyn-cli-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        at org.apache.brooklyn.cli.AbstractMain.execCli(AbstractMain.java:244) [brooklyn-cli-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        at io.cloudsoft.amp.Main.main(Main.java:32) [amp-launcher-3.1.0-20160125.1743-p2.jar:na]
Caused by: java.util.concurrent.ExecutionException: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: Failure rebinding: problem rebinding entity j1M7T5XG (DockerInfrastructureImpl{id=j1M7T5XG}): Cannot instantiate location 'LocationDefinition{id='gzuSFMac
', name='my-docker-cloud-vagrant', spec='docker:j1M7T5XG:(name="my-docker-cloud-vagrant")', config={provisioner=FixedListMachineProvisioningLocation{id=DtPfBrpb, name=FixedListMachineProvisioningLocation:DtPf}, strategies=[DockerAwarePlacementStrategy(MaxContainersPlace
mentStrategy@j8yVexHt), DockerAwarePlacementStrategy(BreadthFirstPlacementStrategy@ce2SXY0W)]}}' pointing at docker:j1M7T5XG:(name="my-docker-cloud-vagrant"): java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.7.0_71]
        at java.util.concurrent.FutureTask.get(FutureTask.java:188) ~[na:1.7.0_71]
        at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:63) ~[guava-17.0.jar:na]
        at org.apache.brooklyn.util.core.task.BasicTask.get(BasicTask.java:361) ~[brooklyn-core-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        at org.apache.brooklyn.core.mgmt.rebind.RebindManagerImpl.rebind(RebindManagerImpl.java:505) ~[brooklyn-core-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        ... 12 common frames omitted
org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: Failure rebinding: problem rebinding entity j1M7T5XG (DockerInfrastructureImpl{id=j1M7T5XG}): Cannot instantiate location 'LocationDefinition{id='gzuSFMac', name='my-docker-cloud-vagrant', spec='docker:j1M7
T5XG:(name="my-docker-cloud-vagrant")', config={provisioner=FixedListMachineProvisioningLocation{id=DtPfBrpb, name=FixedListMachineProvisioningLocation:DtPf}, strategies=[DockerAwarePlacementStrategy(MaxContainersPlacementStrategy@j8yVexHt), DockerAwarePlacementStrategy
(BreadthFirstPlacementStrategy@ce2SXY0W)]}}' pointing at docker:j1M7T5XG:(name="my-docker-cloud-vagrant"): java.lang.NullPointerException
        at org.apache.brooklyn.util.exceptions.Exceptions.create(Exceptions.java:321) ~[brooklyn-utils-common-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        at org.apache.brooklyn.core.mgmt.rebind.RebindExceptionHandlerImpl.onDoneImpl(RebindExceptionHandlerImpl.java:497) ~[brooklyn-core-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        at org.apache.brooklyn.core.mgmt.rebind.RebindExceptionHandlerImpl.onDone(RebindExceptionHandlerImpl.java:413) ~[brooklyn-core-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        at org.apache.brooklyn.core.mgmt.rebind.RebindIteration.run(RebindIteration.java:267) ~[brooklyn-core-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        at org.apache.brooklyn.core.mgmt.rebind.RebindManagerImpl.rebindImpl(RebindManagerImpl.java:552) ~[brooklyn-core-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        at org.apache.brooklyn.core.mgmt.rebind.RebindManagerImpl$3.call(RebindManagerImpl.java:502) ~[brooklyn-core-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        at org.apache.brooklyn.core.mgmt.rebind.RebindManagerImpl$3.call(RebindManagerImpl.java:500) ~[brooklyn-core-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        at org.apache.brooklyn.util.core.task.BasicExecutionManager$SubmissionCallable.call(BasicExecutionManager.java:499) ~[brooklyn-core-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~[na:1.7.0_71]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:1.7.0_71]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.7.0_71]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_71]
Caused by: java.lang.IllegalStateException: problem rebinding entity j1M7T5XG (DockerInfrastructureImpl{id=j1M7T5XG})
        at org.apache.brooklyn.core.mgmt.rebind.RebindExceptionHandlerImpl.onRebindFailed(RebindExceptionHandlerImpl.java:304) ~[brooklyn-core-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        at org.apache.brooklyn.core.mgmt.rebind.RebindIteration.reconstructEverything(RebindIteration.java:625) ~[brooklyn-core-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        at org.apache.brooklyn.core.mgmt.rebind.RebindIteration.doRun(RebindIteration.java:242) ~[brooklyn-core-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        at org.apache.brooklyn.core.mgmt.rebind.InitialFullRebindIteration.doRun(InitialFullRebindIteration.java:69) ~[brooklyn-core-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        at org.apache.brooklyn.core.mgmt.rebind.RebindIteration.run(RebindIteration.java:265) ~[brooklyn-core-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        ... 8 common frames omitted
Caused by: java.lang.IllegalStateException: Cannot instantiate location 'LocationDefinition{id='gzuSFMac', name='my-docker-cloud-vagrant', spec='docker:j1M7T5XG:(name="my-docker-cloud-vagrant")', config={provisioner=FixedListMachineProvisioningLocation{id=DtPfBrpb, name
=FixedListMachineProvisioningLocation:DtPf}, strategies=[DockerAwarePlacementStrategy(MaxContainersPlacementStrategy@j8yVexHt), DockerAwarePlacementStrategy(BreadthFirstPlacementStrategy@ce2SXY0W)]}}' pointing at docker:j1M7T5XG:(name="my-docker-cloud-vagrant"): java.la
ng.NullPointerException
        at org.apache.brooklyn.core.location.BasicLocationRegistry.resolve(BasicLocationRegistry.java:491) ~[patch-BasicLocationRegistry-include-cause.jar:0.9.0-20160125.1743-p1]
        at org.apache.brooklyn.core.location.BasicLocationRegistry.resolve(BasicLocationRegistry.java:459) ~[patch-BasicLocationRegistry-include-cause.jar:0.9.0-20160125.1743-p1]
        at brooklyn.entity.container.DockerUtils$ReloadDockerLocation.reloaded(DockerUtils.java:392) ~[brooklyn-clocker-docker-1.1.0-20160125.1743-p1.jar:1.1.0-20160125.1743-p1]
        at brooklyn.entity.container.docker.DockerInfrastructureImpl.rebind(DockerInfrastructureImpl.java:346) ~[brooklyn-clocker-docker-1.1.0-20160125.1743-p1.jar:1.1.0-20160125.1743-p1]
        at org.apache.brooklyn.core.mgmt.rebind.AbstractBrooklynObjectRebindSupport.reconstruct(AbstractBrooklynObjectRebindSupport.java:69) ~[brooklyn-core-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        at org.apache.brooklyn.core.mgmt.rebind.RebindIteration.reconstructEverything(RebindIteration.java:623) ~[brooklyn-core-0.9.0-20160125.1743-p1.jar:0.9.0-20160125.1743-p1]
        ... 11 common frames omitted
Caused by: java.lang.NullPointerException: null
        at brooklyn.location.docker.DockerResolver.newLocationFromString(DockerResolver.java:155) ~[brooklyn-clocker-docker-1.1.0-20160125.1743-p1.jar:1.1.0-20160125.1743-p1]
        at brooklyn.location.docker.DockerResolver.newLocationFromString(DockerResolver.java:84) ~[brooklyn-clocker-docker-1.1.0-20160125.1743-p1.jar:1.1.0-20160125.1743-p1]
        at org.apache.brooklyn.core.location.BasicLocationRegistry.resolve(BasicLocationRegistry.java:353) ~[patch-BasicLocationRegistry-include-cause.jar:0.9.0-20160125.1743-p1]
        at org.apache.brooklyn.core.location.BasicLocationRegistry.resolve(BasicLocationRegistry.java:487) ~[patch-BasicLocationRegistry-include-cause.jar:0.9.0-20160125.1743-p1]
        ... 16 common frames omitted
```

**Comment by aledsage** [comment]
#### My reading of the code

I presume we're "only" calling `DockerUtils.ReloadDockerLocation` on rebind because the defined locations are not persisted - the `DockerInfrastructureImpl` previously called `getManagementContext().getLocationRegistry().updateDefinedLocation(definition)`.

When folk use this `LocationDefinition` for deploying their apps, it will return the same location object (or on the very first usage, create a new one - possibly a race condition for that?). This is because `DockerResolver` is given the spec, and will find the `DockerLocation` instance with the matching `DockerInfrastructure` "owner".


#### Persisted state

I see the following LocationDefinition persisted in the DockerInfrastructure entity:

```
        <brooklyn.management.propertiesReloadListener>
          <brooklyn.entity.container.DockerUtils_-ReloadDockerLocation>
            <context class="org.apache.brooklyn.core.mgmt.internal.LocalManagementContext" reference="../../../../config/docker.container.strategies/MutableList/list/brooklyn.location.docker.strategy.MaxContainersPlacementStrategy/managementContext"/>
            <definition class="org.apache.brooklyn.core.location.BasicLocationDefinition">
              <id>wQ7TbtXr</id>
              <name>my-docker-cloud</name>
              <spec>docker:C3p3JSSk:(name=&quot;my-docker-cloud&quot;)</spec>
              <config class="com.google.common.collect.RegularImmutableMap">
                <entry>
                  <string>provisioner</string>
                  <locationProxy>EPVYE4LA</locationProxy>
                </entry>
                <entry>
                  <string>strategies</string>
                  <list>
                    <brooklyn.location.docker.strategy.MaxContainersPlacementStrategy reference="../../../../../../../../config/docker.container.strategies/MutableList/list/brooklyn.location.docker.strategy.MaxContainersPlacementStrategy"/>
                    <brooklyn.location.docker.strategy.BreadthFirstPlacementStrategy reference="../../../../../../../../config/docker.container.strategies/MutableList/list/brooklyn.location.docker.strategy.BreadthFirstPlacementStrategy"/>
                  </list>
                </entry>
              </config>
            </definition>
          </brooklyn.entity.container.DockerUtils_-ReloadDockerLocation>
        </brooklyn.management.propertiesReloadListener>
```


#### Solution/Discussion?

What is the best long-term fix for this? How do we want Brooklyn to behave so we don't have to do this in the clocker code?

Do we want to automatically persisted `LocationDefinition`s? 
(not convinced - the catalog feels like the better place to define location specs).

Do we want Clocker to instead add a new catalog entry for the location spec? 
(would that be enough, or would it *also* have to add the `LocationDefinition` for it to appear in the drop-down list)?

Or do we want to change the way we're registering the location / locationDefinition? 
For example, the `DockerInfrastructure` could immediately instantiate the location object, and use a resolver that maps from a name to a specific pre-existing location instance. It could be the location instance itself that registers itself? The `DockerLocation`'s `rebind()` implementation could register itself (i.e. register a `LocationDefinition` for itself).

Or maybe there is some new concept / utility in Brooklyn we should add - but that would need to be compelling.

**Comment by aledsage** [comment]
See suggested pattern to fix this, in https://github.com/apache/brooklyn-server/pull/59
