### ISSUE TITLE
Node.js demo app fails (ClassCastException in DockerUtils.getContainerPorts)

### ISSUE THREAD

**Issue by aledsage** [brooklyncentral/clocker#298]
With clocker master, deploying the "Node.js Demo Application" from the default catalog gives the error below:

```
Failed after 7ms: Error invoking start at DockerContainerImpl{id=drfhrCvm}: java.lang.String cannot be cast to org.apache.brooklyn.core.sensor.PortAttributeSensorAndConfigKey

org.apache.brooklyn.core.mgmt.internal.EffectorUtils$EffectorCallPropagatedRuntimeException: Error invoking start at DockerContainerImpl{id=drfhrCvm}: java.lang.String cannot be cast to org.apache.brooklyn.core.sensor.PortAttributeSensorAndConfigKey
	at org.apache.brooklyn.core.mgmt.internal.EffectorUtils$EffectorCallPropagatedRuntimeException.propagate(EffectorUtils.java:299)
	at org.apache.brooklyn.core.mgmt.internal.EffectorUtils$EffectorCallPropagatedRuntimeException.access$100(EffectorUtils.java:266)
	at org.apache.brooklyn.core.mgmt.internal.EffectorUtils.handleEffectorException(EffectorUtils.java:306)
	at org.apache.brooklyn.core.mgmt.internal.EffectorUtils.invokeMethodEffector(EffectorUtils.java:260)
	at org.apache.brooklyn.core.effector.MethodEffector.call(MethodEffector.java:149)
	at org.apache.brooklyn.core.entity.trait.Startable$StartEffectorBody.call(Startable.java:56)
	at org.apache.brooklyn.core.entity.trait.Startable$StartEffectorBody.call(Startable.java:50)
	at org.apache.brooklyn.core.effector.EffectorTasks$EffectorBodyTaskFactory$1.call(EffectorTasks.java:82)
	at org.apache.brooklyn.util.core.task.DynamicSequentialTask$DstJob.call(DynamicSequentialTask.java:359)
	at org.apache.brooklyn.util.core.task.BasicExecutionManager$SubmissionCallable.call(BasicExecutionManager.java:519)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.lang.ClassCastException: java.lang.String cannot be cast to org.apache.brooklyn.core.sensor.PortAttributeSensorAndConfigKey
	at org.apache.brooklyn.core.mgmt.internal.AbstractManagementContext.invokeEffectorMethodSync(AbstractManagementContext.java:337)
	at org.apache.brooklyn.core.mgmt.internal.EffectorUtils.invokeMethodEffector(EffectorUtils.java:255)
	... 10 more
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to org.apache.brooklyn.core.sensor.PortAttributeSensorAndConfigKey
	at clocker.docker.entity.util.DockerUtils.getContainerPorts(DockerUtils.java:415)
	at clocker.docker.entity.container.DockerContainerImpl.getDockerTemplateOptions(DockerContainerImpl.java:380)
	at clocker.docker.entity.container.DockerContainerImpl.createLocation(DockerContainerImpl.java:510)
	at clocker.docker.entity.container.DockerContainerImpl.start(DockerContainerImpl.java:670)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:149)
	at groovy.lang.MetaObjectProtocol$invokeMethod.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at groovy.lang.MetaObjectProtocol$invokeMethod.call(Unknown Source)
	at org.apache.brooklyn.util.groovy.GroovyJavaMethods.invokeMethodOnMetaClass(GroovyJavaMethods.java:191)
	at org.apache.brooklyn.core.mgmt.internal.AbstractManagementContext.invokeEffectorMethodLocal(AbstractManagementContext.java:309)
	at org.apache.brooklyn.core.mgmt.internal.AbstractManagementContext.invokeEffectorMethodSync(AbstractManagementContext.java:333)
	... 11 more
```

This is because the default.catalog.bom file uses:

```
            docker.container.openPorts.configKeys:
            - "http.port"
```

Instead of:

```
            docker.container.openPorts.configKeys:
            - $brooklyn:sensor("http.port")
```

**Comment by aledsage** [comment]
Should be fixed by https://github.com/brooklyncentral/clocker/pull/302 - once that is reviewed+merged, we can close this bug. Suggest we back-port this to 1.1.x branch as well @grkvlt
